from __future__ import annotations

from enum import Enum, IntEnum


class StrEnum(str, Enum):
    """字符串枚举基类，便于 JSON 序列化。"""


class FieldType(StrEnum):
    FIELD_TYPE_TEXT = "FIELD_TYPE_TEXT"
    FIELD_TYPE_NUMBER = "FIELD_TYPE_NUMBER"
    FIELD_TYPE_CHECKBOX = "FIELD_TYPE_CHECKBOX"
    FIELD_TYPE_DATE_TIME = "FIELD_TYPE_DATE_TIME"
    FIELD_TYPE_IMAGE = "FIELD_TYPE_IMAGE"
    FIELD_TYPE_ATTACHMENT = "FIELD_TYPE_ATTACHMENT"
    FIELD_TYPE_USER = "FIELD_TYPE_USER"
    FIELD_TYPE_URL = "FIELD_TYPE_URL"
    FIELD_TYPE_SELECT = "FIELD_TYPE_SELECT"
    FIELD_TYPE_CREATED_USER = "FIELD_TYPE_CREATED_USER"
    FIELD_TYPE_MODIFIED_USER = "FIELD_TYPE_MODIFIED_USER"
    FIELD_TYPE_CREATED_TIME = "FIELD_TYPE_CREATED_TIME"
    FIELD_TYPE_MODIFIED_TIME = "FIELD_TYPE_MODIFIED_TIME"
    FIELD_TYPE_PROGRESS = "FIELD_TYPE_PROGRESS"
    FIELD_TYPE_PHONE_NUMBER = "FIELD_TYPE_PHONE_NUMBER"
    FIELD_TYPE_EMAIL = "FIELD_TYPE_EMAIL"
    FIELD_TYPE_SINGLE_SELECT = "FIELD_TYPE_SINGLE_SELECT"
    FIELD_TYPE_REFERENCE = "FIELD_TYPE_REFERENCE"
    FIELD_TYPE_LOCATION = "FIELD_TYPE_LOCATION"
    FIELD_TYPE_FORMULA = "FIELD_TYPE_FORMULA"
    FIELD_TYPE_CURRENCY = "FIELD_TYPE_CURRENCY"
    FIELD_TYPE_WWGROUP = "FIELD_TYPE_WWGROUP"
    FIELD_TYPE_AUTONUMBER = "FIELD_TYPE_AUTONUMBER"
    FIELD_TYPE_PERCENTAGE = "FIELD_TYPE_PERCENTAGE"
    FIELD_TYPE_BARCODE = "FIELD_TYPE_BARCODE"


class ViewType(StrEnum):
    VEW_UNKNOWN = "VEW_UNKNOWN"
    VIEW_TYPE_GRID = "VIEW_TYPE_GRID"
    VIEW_TYPE_KANBAN = "VIEW_TYPE_KANBAN"
    VIEW_TYPE_GALLERY = "VIEW_TYPE_GALLERY"
    VIEW_TYPE_GANTT = "VIEW_TYPE_GANTT"
    VIEW_TYPE_CALENDAR = "VIEW_TYPE_CALENDAR"


class CellValueKeyType(StrEnum):
    CELL_VALUE_KEY_TYPE_FIELD_TITLE = "CELL_VALUE_KEY_TYPE_FIELD_TITLE"
    CELL_VALUE_KEY_TYPE_FIELD_ID = "CELL_VALUE_KEY_TYPE_FIELD_ID"


class Operator(StrEnum):
    OPERATOR_UNKNOWN = "OPERATOR_UNKNOWN"
    OPERATOR_IS = "OPERATOR_IS"
    OPERATOR_IS_NOT = "OPERATOR_IS_NOT"
    OPERATOR_CONTAINS = "OPERATOR_CONTAINS"
    OPERATOR_DOES_NOT_CONTAIN = "OPERATOR_DOES_NOT_CONTAIN"
    OPERATOR_IS_GREATER = "OPERATOR_IS_GREATER"
    OPERATOR_IS_GREATER_OR_EQUAL = "OPERATOR_IS_GREATER_OR_EQUAL"
    OPERATOR_IS_LESS = "OPERATOR_IS_LESS"
    OPERATOR_IS_LESS_OR_EQUAL = "OPERATOR_IS_LESS_OR_EQUAL"
    OPERATOR_IS_EMPTY = "OPERATOR_IS_EMPTY"
    OPERATOR_IS_NOT_EMPTY = "OPERATOR_IS_NOT_EMPTY"


class DateTimeType(StrEnum):
    DATE_TIME_TYPE_DETAIL_DATE = "DATE_TIME_TYPE_DETAIL_DATE"
    DATE_TIME_TYPE_TODAY = "DATE_TIME_TYPE_TODAY"
    DATE_TIME_TYPE_TOMORROW = "DATE_TIME_TYPE_TOMORROW"
    DATE_TIME_TYPE_YESTERDAY = "DATE_TIME_TYPE_YESTERDAY"
    DATE_TIME_TYPE_CURRENT_WEEK = "DATE_TIME_TYPE_CURRENT_WEEK"
    DATE_TIME_TYPE_LAST_WEEK = "DATE_TIME_TYPE_LAST_WEEK"
    DATE_TIME_TYPE_CURRENT_MONTH = "DATE_TIME_TYPE_CURRENT_MONTH"
    DATE_TIME_TYPE_THE_PAST_7_DAYS = "DATE_TIME_TYPE_THE_PAST_7_DAYS"
    DATE_TIME_TYPE_THE_NEXT_7_DAYS = "DATE_TIME_TYPE_THE_NEXT_7_DAYS"
    DATE_TIME_TYPE_LAST_MONTH = "DATE_TIME_TYPE_LAST_MONTH"
    DATE_TIME_TYPE_THE_PAST_30_DAYS = "DATE_TIME_TYPE_THE_PAST_30_DAYS"
    DATE_TIME_TYPE_THE_NEXT_30_DAYS = "DATE_TIME_TYPE_THE_NEXT_30_DAYS"


class Conjunction(StrEnum):
    CONJUNCTION_AND = "CONJUNCTION_AND"
    CONJUNCTION_OR = "CONJUNCTION_OR"


class ViewColorConditionType(StrEnum):
    VIEW_COLOR_CONDITION_TYPE_ROW = "VIEW_COLOR_CONDITION_TYPE_ROW"
    VIEW_COLOR_CONDITION_TYPE_COLUMN = "VIEW_COLOR_CONDITION_TYPE_COLUMN"
    VIEW_COLOR_CONDITION_TYPE_CELL = "VIEW_COLOR_CONDITION_TYPE_CELL"


class ViewColor(StrEnum):
    fillColorGray_5 = "fillColorGray_5"
    accentBlueLighten_5 = "accentBlueLighten_5"
    chromeCyanLighten_5 = "chromeCyanLighten_5"
    chromeMintLighten_5 = "chromeMintLighten_5"
    chromeRedLighten_5 = "chromeRedLighten_5"
    chromeOrangeLighten_5 = "chromeOrangeLighten_5"
    chromeAmberLighten_5 = "chromeAmberLighten_5"
    chromeVioletLighten_5 = "chromeVioletLighten_5"
    chromePinkLighten_5 = "chromePinkLighten_5"
    fillColorGray_4 = "fillColorGray_4"
    accentBlueLighten_4 = "accentBlueLighten_4"
    chromeCyanLighten_4 = "chromeCyanLighten_4"
    chromeMintLighten_4 = "chromeMintLighten_4"
    chromeRedLighten_4 = "chromeRedLighten_4"
    chromeOrangeLighten_4 = "chromeOrangeLighten_4"
    chromeAmberLighten_4 = "chromeAmberLighten_4"
    chromeVioletLighten_4 = "chromeVioletLighten_4"
    chromePinkLighten_4 = "chromePinkLighten_4"
    fillColorGray_3 = "fillColorGray_3"
    accentBlueLighten_3 = "accentBlueLighten_3"
    chromeCyanLighten_3 = "chromeCyanLighten_3"
    chromeMintLighten_3 = "chromeMintLighten_3"
    chromeRedLighten_3 = "chromeRedLighten_3"
    chromeOrangeLighten_3 = "chromeOrangeLighten_3"
    chromeAmberLighten_3 = "chromeAmberLighten_3"
    chromeVioletLighten_3 = "chromeVioletLighten_3"
    chromePinkLighten_3 = "chromePinkLighten_3"


class LinkType(StrEnum):
    LINK_TYPE_PURE_TEXT = "LINK_TYPE_PURE_TEXT"
    LINK_TYPE_ICON_TEXT = "LINK_TYPE_ICON_TEXT"


class DisplayMode(StrEnum):
    DISPLAY_MODE_LIST = "DISPLAY_MODE_LIST"
    DISPLAY_MODE_GRID = "DISPLAY_MODE_GRID"


class LocationInputType(StrEnum):
    LOCATION_INPUT_TYPE_MANUAL = "LOCATION_INPUT_TYPE_MANUAL"
    LOCATION_INPUT_TYPE_AUTO = "LOCATION_INPUT_TYPE_AUTO"


class NumberType(StrEnum):
    NUMBER_TYPE_INCR = "NUMBER_TYPE_INCR"
    NUMBER_TYPE_CUSTOM = "NUMBER_TYPE_CUSTOM"


class NumberRuleType(StrEnum):
    NUMBER_RULE_TYPE_INCR = "NUMBER_RULE_TYPE_INCR"
    NUMBER_RULE_TYPE_FIXED_CHAR = "NUMBER_RULE_TYPE_FIXED_CHAR"
    NUMBER_RULE_TYPE_TIME = "NUMBER_RULE_TYPE_TIME"


class CurrencyType(StrEnum):
    CURRENCY_TYPE_CNY = "CURRENCY_TYPE_CNY"
    CURRENCY_TYPE_USD = "CURRENCY_TYPE_USD"
    CURRENCY_TYPE_EUR = "CURRENCY_TYPE_EUR"
    CURRENCY_TYPE_GBP = "CURRENCY_TYPE_GBP"
    CURRENCY_TYPE_JPY = "CURRENCY_TYPE_JPY"
    CURRENCY_TYPE_KRW = "CURRENCY_TYPE_KRW"
    CURRENCY_TYPE_HKD = "CURRENCY_TYPE_HKD"
    CURRENCY_TYPE_MOP = "CURRENCY_TYPE_MOP"
    CURRENCY_TYPE_TWD = "CURRENCY_TYPE_TWD"
    CURRENCY_TYPE_AED = "CURRENCY_TYPE_AED"
    CURRENCY_TYPE_AUD = "CURRENCY_TYPE_AUD"
    CURRENCY_TYPE_BRL = "CURRENCY_TYPE_BRL"
    CURRENCY_TYPE_CAD = "CURRENCY_TYPE_CAD"
    CURRENCY_TYPE_CHF = "CURRENCY_TYPE_CHF"
    CURRENCY_TYPE_IDR = "CURRENCY_TYPE_IDR"
    CURRENCY_TYPE_INR = "CURRENCY_TYPE_INR"
    CURRENCY_TYPE_MXN = "CURRENCY_TYPE_MXN"
    CURRENCY_TYPE_MYR = "CURRENCY_TYPE_MYR"
    CURRENCY_TYPE_PHP = "CURRENCY_TYPE_PHP"
    CURRENCY_TYPE_PLN = "CURRENCY_TYPE_PLN"
    CURRENCY_TYPE_RUB = "CURRENCY_TYPE_RUB"
    CURRENCY_TYPE_SGD = "CURRENCY_TYPE_SGD"
    CURRENCY_TYPE_THB = "CURRENCY_TYPE_THB"
    CURRENCY_TYPE_TRY = "CURRENCY_TYPE_TRY"
    CURRENCY_TYPE_VND = "CURRENCY_TYPE_VND"


class SheetType(StrEnum):
    dashboard = "dashboard"
    external = "external"
    smartsheet = "smartsheet"


class DecimalPlaces(IntEnum):
    SHOW_ORIGIN = -1
    INT = 0
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4


class Style(IntEnum):
    STYLE_1 = 1
    STYLE_2 = 2
    STYLE_3 = 3
    STYLE_4 = 4
    STYLE_5 = 5
    STYLE_6 = 6
    STYLE_7 = 7
    STYLE_8 = 8
    STYLE_9 = 9
    STYLE_10 = 10
    STYLE_11 = 11
    STYLE_12 = 12
    STYLE_13 = 13
    STYLE_14 = 14
    STYLE_15 = 15
    STYLE_16 = 16
    STYLE_17 = 17
    STYLE_18 = 18
    STYLE_19 = 19
    STYLE_20 = 20
    STYLE_21 = 21
    STYLE_22 = 22
    STYLE_23 = 23
    STYLE_24 = 24
    STYLE_25 = 25
    STYLE_26 = 26
    STYLE_27 = 27
